[package]
name = "targeter"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
eyre = "0.6"
chrono = "0.4"
bytefmt = "0.1"
notify = "8"
num_cpus = "1.16"
regex = "1"
tracing = "0.1"
tracing-chrome = "0.7"
tracing-subscriber = "0.3"
parallel-disk-usage = { version = "0.24.0", default-features = false }
ignore = "0.4.33"
rayon = "1.12.0"
