[package]
name = "targeter"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
eyre = "0.6"
timeago = { version = "0.6", default-features = false }
bytefmt = "0.1"
notify = "8"
num_cpus = "1.16"
regex = "1"
tracing = "0.1"
tracing-chrome = "0.7"
tracing-subscriber = "0.3"
ignore = "0.4.33"
rayon = "1.12.0"
crossbeam-channel = "0.5.16"
